export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: string;
  originalPrice?: string;
  specs: string;
  rating: number;
  image: string;
  description: string;
  longDescription: string;
  features: string[];
  specifications: {
    [key: string]: string;
  };
  warranty: string;
  availability: string;
  inStock: boolean;
  stockQuantity: number;
}

export const productsData: Product[] = [
  // LAPTOPS - Dell, HP, Apple, Lenovo
  {
    id: "dell-gaming-g15",
    name: "Dell G15 Gaming Laptop",
    brand: "Dell",
    category: "laptops",
    price: "145,000 KES",
    originalPrice: "165,000 KES",
    specs: "RTX 4060, i7-13th Gen, 16GB RAM, 512GB SSD",
    rating: 4.8,
    image: "/images/products/gaming-laptop.jpg",
    description:
      "Powerful gaming laptop with RTX 4060 graphics card and latest Intel processor.",
    longDescription:
      "The Dell G15 is engineered for gamers and content creators seeking high performance. Built with NVIDIA RTX 4060 graphics, Intel Core i7-13th Gen processor, and 16GB DDR5 RAM. Features a 15.6-inch 165Hz display for smooth gameplay, advanced cooling system with dual fans, and up to 10 hours battery life. Perfect for gaming, 3D rendering, video editing, and professional work.",
    features: [
      "NVIDIA RTX 4060 (6GB GDDR6)",
      "Intel Core i7-13700H (14-core processor)",
      "16GB DDR5 RAM (upgradeable to 32GB)",
      "512GB NVMe SSD",
      '15.6" 165Hz FHD IPS Display',
      "Backlit Mechanical Keyboard",
      "Dual Fan Cooling System",
      "Thunderbolt 4 & USB Type-C",
      "Windows 11 Pro",
      "Free Antivirus (1 Year)",
    ],
    specifications: {
      Processor: "Intel Core i7-13700H",
      Graphics: "NVIDIA RTX 4060 6GB",
      Memory: "16GB DDR5 RAM",
      Storage: "512GB NVMe SSD",
      Display: '15.6" FHD (1920x1080) 165Hz IPS',
      Battery: "56Wh, Up to 10 hours",
      Weight: "2.65 kg",
      Ports: "2x USB 3.2, 1x Thunderbolt 4, 1x HDMI 2.1, 1x 3.5mm Audio",
      OS: "Windows 11 Pro",
      Color: "Dark Shadow Grey",
    },
    warranty:
      "2 Years International Warranty + 3 Years Accidental Damage Protection",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 5,
  },
  {
    id: "hp-pavilion-15",
    name: "HP Pavilion 15 Business Laptop",
    brand: "HP",
    category: "laptops",
    price: "75,000 KES",
    originalPrice: "85,000 KES",
    specs: "AMD Ryzen 5, 8GB RAM, 256GB SSD, FHD Display",
    rating: 4.6,
    image: "/images/products/ultrabook.jpg",
    description:
      "Versatile business laptop combining portability with reliable performance for professionals.",
    longDescription:
      "HP Pavilion 15 is designed for business professionals and students who need balanced performance and portability. Features AMD Ryzen 5 5500U processor, 8GB DDR4 RAM, and 256GB SSD for fast boot times. The 15.6-inch FHD display with micro-edge bezels provides excellent viewing experience. Built with sustainable materials and includes HP Sure Click security feature. Ideal for productivity, web browsing, and light creative work.",
    features: [
      "AMD Ryzen 5 5500U Processor",
      "8GB DDR4 RAM",
      "256GB SSD NVMe Storage",
      '15.6" FHD (1920x1080) Display',
      "AMD Radeon Graphics",
      "HP Sure Click Security",
      "5MP HD Webcam with Privacy Shutter",
      "Stereo Speakers with DTS Audio",
      "Windows 11 Home",
      "HP Quick Launch Key",
    ],
    specifications: {
      Processor: "AMD Ryzen 5 5500U (6-core)",
      Graphics: "AMD Radeon Graphics",
      Memory: "8GB DDR4 RAM",
      Storage: "256GB SSD NVMe",
      Display: '15.6" FHD (1920x1080) IPS',
      Battery: "52.5Wh, Up to 10 hours",
      Weight: "1.75 kg",
      Ports:
        "1x USB 3.2 Type-A, 2x USB 2.0, 1x HDMI, 1x 3.5mm Audio, 1x SD Card Reader",
      OS: "Windows 11 Home",
      Color: "Natural Silver",
    },
    warranty: "1 Year International Warranty + Free Technical Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 8,
  },
  {
    id: "apple-macbook-pro-14",
    name: 'Apple MacBook Pro 14" M3',
    brand: "Apple",
    category: "laptops",
    price: "250,000 KES",
    originalPrice: "280,000 KES",
    specs: "Apple M3 Chip, 8GB RAM, 512GB SSD, Retina Display",
    rating: 4.9,
    image: "/images/products/gaming-laptop.jpg",
    description:
      "Premium ultrabook with Apple's powerful M3 chip and stunning Liquid Retina display.",
    longDescription:
      "MacBook Pro 14-inch with Apple M3 chip delivers exceptional performance for creative professionals. Features 8GB unified memory, 512GB SSD storage, and 14-inch Liquid Retina XDR display with ProMotion technology. Built with aluminum chassis, MagSafe charging, and up to 17 hours battery life. Includes three Thunderbolt 4 ports, HDMI, and SD card slot. Perfect for video editing, 3D modeling, software development, and creative work.",
    features: [
      "Apple M3 Chip (8-core CPU, 10-core GPU)",
      "8GB Unified Memory",
      "512GB SSD Storage",
      '14" Liquid Retina XDR Display',
      "3072 x 1920 Resolution",
      "ProMotion 120Hz Technology",
      "MagSafe Charging",
      "3x Thunderbolt 4 Ports",
      "HDMI & SD Card Slot",
      "Up to 17 Hours Battery Life",
    ],
    specifications: {
      Processor: "Apple M3 Chip",
      Memory: "8GB Unified Memory",
      Storage: "512GB SSD",
      Display: '14" Liquid Retina XDR (3072 x 1920)',
      Graphics: "Integrated 10-core GPU",
      Battery: "Up to 17 hours",
      Weight: "1.6 kg",
      Ports: "3x Thunderbolt 4, 1x HDMI, 1x SD Card Slot, 1x MagSafe",
      OS: "macOS Sonoma",
      Color: "Space Black / Silver",
    },
    warranty: "1 Year Limited Warranty + AppleCare+ Available (2-4 Years)",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 3,
  },
  {
    id: "lenovo-thinkpad-x1",
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    brand: "Lenovo",
    category: "laptops",
    price: "180,000 KES",
    originalPrice: "205,000 KES",
    specs: "Intel i7-1365U, 16GB RAM, 512GB SSD, WUXGA Display",
    rating: 4.7,
    image: "/images/products/ultrabook.jpg",
    description:
      "Ultra-slim business laptop with legendary ThinkPad durability and keyboard quality.",
    longDescription:
      "Lenovo ThinkPad X1 Carbon Gen 11 is the gold standard for business laptops. Features Intel Core i7-1365U processor, 16GB LPDDR5 RAM, and 512GB SSD. The 14-inch WUXGA display is optimized for productivity with anti-glare coating. Built with magnesium-aluminum chassis, mil-spec durability, and advanced security features including infrared camera and fingerprint reader. Up to 13 hours battery life with rapid charging.",
    features: [
      "Intel Core i7-1365U Processor",
      "16GB LPDDR5 RAM",
      "512GB SSD Storage",
      '14" WUXGA (1920x1200) Display',
      "Anti-glare Coating",
      "Intel Iris Xe Graphics",
      "ThinkPad Legendary Keyboard",
      "Infrared Camera for Secure Login",
      "Fingerprint Reader",
      "Up to 13 Hours Battery Life",
    ],
    specifications: {
      Processor: "Intel Core i7-1365U (10-core)",
      Graphics: "Intel Iris Xe Graphics",
      Memory: "16GB LPDDR5 RAM",
      Storage: "512GB SSD NVMe",
      Display: '14" WUXGA (1920x1200) IPS',
      Battery: "52.5Wh, Up to 13 hours",
      Weight: "1.28 kg",
      Ports: "2x Thunderbolt 4, 2x USB 3.2, 1x HDMI 2.0, 1x 3.5mm Audio",
      OS: "Windows 11 Pro",
      Security: "IR Camera, Fingerprint Reader, TPM 2.0",
    },
    warranty: "3 Years Onsite Hardware Service Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 6,
  },
  {
    id: "dell-inspiron-student",
    name: "Dell Inspiron 15 Student Edition",
    brand: "Dell",
    category: "laptops",
    price: "52,000 KES",
    originalPrice: "59,000 KES",
    specs: "Intel i5, 8GB RAM, 256GB SSD, HD Display",
    rating: 4.5,
    image: "/images/products/budget-laptop.jpg",
    description:
      "Affordable, reliable laptop perfect for students and everyday computing needs.",
    longDescription:
      "Dell Inspiron 15 is specifically designed for students with a focus on affordability and reliability. Equipped with Intel Core i5 processor, 8GB RAM, and 256GB SSD for smooth multitasking. The 15.6-inch HD display provides good visibility for online classes and research. Comes pre-loaded with Microsoft Office Home & Student edition (1 year). Battery lasts up to 8 hours on a single charge, perfect for campus use.",
    features: [
      "Intel Core i5-1235U Processor",
      "8GB DDR4 RAM",
      "256GB SSD Storage",
      '15.6" HD (1366x768) Display',
      "Intel UHD Graphics",
      "Microsoft Office Home & Student (1 Year)",
      "5MP Webcam",
      "Stereo Speakers",
      "Windows 11 Home",
      "Dell Student Discount Support",
    ],
    specifications: {
      Processor: "Intel Core i5-1235U (10-core)",
      Graphics: "Intel UHD Graphics",
      Memory: "8GB DDR4 RAM",
      Storage: "256GB SSD",
      Display: '15.6" HD (1366x768)',
      Battery: "40Wh, Up to 8 hours",
      Weight: "1.79 kg",
      Ports:
        "2x USB 3.2, 1x USB 2.0, 1x HDMI, 1x 3.5mm Audio, 1x SD Card Reader",
      OS: "Windows 11 Home",
      Software: "MS Office Home & Student (1 Year)",
    },
    warranty: "1 Year Limited Warranty + Free Technical Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 12,
  },
  {
    id: "hp-pavilion-gaming",
    name: "HP Pavilion Gaming 16",
    brand: "HP",
    category: "laptops",
    price: "135,000 KES",
    originalPrice: "155,000 KES",
    specs: "RTX 4050, AMD Ryzen 7, 16GB RAM, 512GB SSD",
    rating: 4.7,
    image: "/images/products/gaming-laptop.jpg",
    description:
      "High-performance gaming laptop with RTX graphics and large display for immersive gaming.",
    longDescription:
      "HP Pavilion Gaming 16 combines powerful performance with a large 16-inch display perfect for gaming and content creation. Features NVIDIA RTX 4050 graphics, AMD Ryzen 7 7700H processor, 16GB DDR5 RAM, and 512GB SSD. The 16-inch FHD+ 144Hz display delivers smooth, immersive gaming experience. Equipped with HP's Omen Tempest cooling technology, Dual Speakers with DTS Audio, and backlit keyboard. Up to 9 hours battery life.",
    features: [
      "NVIDIA RTX 4050 (6GB)",
      "AMD Ryzen 7 7700H Processor",
      "16GB DDR5 RAM",
      "512GB SSD NVMe",
      '16" FHD+ (1920x1200) 144Hz Display',
      "Omen Tempest Cooling Technology",
      "Backlit Keyboard",
      "Dual Speakers with DTS Audio",
      "Windows 11 Home",
      "Free Gaming Software Bundles",
    ],
    specifications: {
      Processor: "AMD Ryzen 7 7700H (8-core)",
      Graphics: "NVIDIA RTX 4050 6GB",
      Memory: "16GB DDR5 RAM",
      Storage: "512GB SSD NVMe",
      Display: '16" FHD+ (1920x1200) 144Hz IPS',
      Battery: "84Wh, Up to 9 hours",
      Weight: "2.5 kg",
      Ports:
        "3x USB 3.2, 1x USB-C, 1x HDMI 2.1, 1x 3.5mm Audio, 1x SD Card Reader",
      OS: "Windows 11 Home",
      Cooling: "Dual Fans with Vapor Chamber",
    },
    warranty: "2 Years Limited Hardware Warranty + Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 7,
  },

  // DESKTOPS - Dell, HP
  {
    id: "dell-xps-desktop",
    name: "Dell XPS Tower Gaming Desktop",
    brand: "Dell",
    category: "desktops",
    price: "285,000 KES",
    originalPrice: "320,000 KES",
    specs: "RTX 4070, i7-13700K, 32GB RAM, 1TB SSD",
    rating: 4.8,
    image: "/images/products/gaming-desktop.jpg",
    description:
      "High-end gaming desktop tower with top-tier components for extreme performance.",
    longDescription:
      "Dell XPS Tower is built for demanding gamers and professionals. Features NVIDIA RTX 4070 graphics card, Intel Core i7-13700K processor, 32GB DDR5 RAM, and 1TB NVMe SSD. Designed with excellent cooling and expandability. Includes high-efficiency 850W power supply, tempered glass side panel for showcase, and integrated RGB lighting. Perfect for 4K gaming, 3D rendering, video editing, and professional workloads.",
    features: [
      "NVIDIA RTX 4070 (12GB GDDR6)",
      "Intel Core i7-13700K Processor",
      "32GB DDR5 RAM (upgradeable)",
      "1TB NVMe SSD",
      "Intel Z790 Motherboard",
      "850W 80+ Gold Power Supply",
      "Tempered Glass Side Panel",
      "RGB Lighting Control",
      "Advanced Air Cooling System",
      "Windows 11 Pro Pre-installed",
    ],
    specifications: {
      Processor: "Intel Core i7-13700K (16-core)",
      Graphics: "NVIDIA RTX 4070 12GB",
      Memory: "32GB DDR5 RAM",
      Storage: "1TB NVMe SSD",
      Motherboard: "Intel Z790 Chipset",
      "Power Supply": "850W 80+ Gold Efficiency",
      Case: "XPS Aluminum Tower with Tempered Glass",
      Cooling: "Advanced Air Cooling",
      Connectivity: "2x Thunderbolt 4, 4x USB 3.2, 2x USB 2.0, Audio In/Out",
      OS: "Windows 11 Pro",
    },
    warranty: "3 Years Onsite Hardware Service",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 4,
  },
  {
    id: "hp-pavilion-desktop",
    name: "HP Pavilion TP01 Office Desktop",
    brand: "HP",
    category: "desktops",
    price: "125,000 KES",
    originalPrice: "145,000 KES",
    specs: "AMD Ryzen 5, 16GB RAM, 512GB SSD, Compact Design",
    rating: 4.6,
    image: "/images/products/office-desktop.jpg",
    description:
      "Reliable office desktop with solid performance for productivity and business use.",
    longDescription:
      "HP Pavilion TP01 is ideal for office and business environments. Equipped with AMD Ryzen 5 5600G processor, 16GB DDR4 RAM, and 512GB SSD. The compact design fits well in tight office spaces while maintaining excellent performance. Features multiple USB ports, HDMI connectivity, and built-in Wi-Fi 6. Pre-loaded with Windows 11 Home and includes 1 month free subscription to Microsoft 365. Energy-efficient operation reduces electricity costs.",
    features: [
      "AMD Ryzen 5 5600G Processor",
      "16GB DDR4 RAM",
      "512GB SSD NVMe",
      "Radeon Graphics",
      "Compact Tower Design",
      "Wi-Fi 6 Built-in",
      "Ethernet Connectivity",
      "4x USB 3.2, 4x USB 2.0",
      "Audio In/Out with 3.5mm Jack",
      "Windows 11 Home",
      "Free 1 Month Microsoft 365 Trial",
    ],
    specifications: {
      Processor: "AMD Ryzen 5 5600G (6-core)",
      Graphics: "Radeon Graphics",
      Memory: "16GB DDR4 RAM",
      Storage: "512GB SSD NVMe",
      Motherboard: "AMD B550 Chipset",
      "Power Supply": "400W Standard Efficiency",
      Case: "HP Compact Tower",
      Connectivity: "Wi-Fi 6, Gigabit Ethernet",
      Ports: "4x USB 3.2, 4x USB 2.0, 1x HDMI, 1x VGA, Audio",
      OS: "Windows 11 Home",
    },
    warranty: "1 Year Limited Warranty + Technical Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 6,
  },
  {
    id: "dell-workstation-professional",
    name: "Dell Precision 3000 Workstation",
    brand: "Dell",
    category: "desktops",
    price: "450,000 KES",
    originalPrice: "520,000 KES",
    specs: "Intel Xeon, RTX A2000, 32GB ECC RAM, 1TB SSD",
    rating: 4.9,
    image: "/images/products/workstation.jpg",
    description:
      "Professional workstation for demanding creative and technical work.",
    longDescription:
      "Dell Precision 3000 is engineered for professionals in architecture, engineering, 3D modeling, and video production. Features Intel Xeon processor, NVIDIA RTX A2000 professional graphics, 32GB ECC RAM, and 1TB SSD. Built with error-correcting memory for data integrity, extensive I/O connectivity, and certification for major software applications. Includes 3-year ProSupport with next-business-day onsite service.",
    features: [
      "Intel Xeon W9-2495X Processor",
      "NVIDIA RTX A2000 12GB",
      "32GB ECC DDR5 RAM",
      "1TB SSD NVMe Storage",
      "Expandable to 192GB RAM",
      "Dual 10GbE Ethernet",
      "Thunderbolt 4 Connectivity",
      "Noise-optimized Cooling",
      "ISV Certified for ProE, AutoCAD, MAYA",
      "Windows 11 Pro for Workstations",
    ],
    specifications: {
      Processor: "Intel Xeon W9-2495X",
      Graphics: "NVIDIA RTX A2000 12GB",
      Memory: "32GB ECC DDR5 RAM",
      Storage: "1TB SSD NVMe",
      Motherboard: "Intel W790 Chipset",
      "Power Supply": "1050W Gold Efficiency",
      Case: "Dell Precision Tower",
      Connectivity: "Dual 10GbE, Thunderbolt 4, USB 3.2",
      OS: "Windows 11 Pro for Workstations",
      Certification: "CAD Software Certified",
    },
    warranty: "3 Years ProSupport with Next Business Day Onsite Service",
    availability: "In Stock (Made to Order)",
    inStock: true,
    stockQuantity: 2,
  },

  // MONITORS - HP, Dell, Apple
  {
    id: "dell-s2722dg",
    name: "Dell S2722DG Gaming Monitor",
    brand: "Dell",
    category: "monitors",
    price: "95,000 KES",
    originalPrice: "110,000 KES",
    specs: '27" 165Hz, 1440p QHD, IPS, G-Sync',
    rating: 4.8,
    image: "/images/products/gaming-monitor.jpg",
    description:
      "High-performance gaming monitor with fast refresh rate and excellent color accuracy.",
    longDescription:
      "Dell S2722DG is a 27-inch gaming monitor with 1440p QHD resolution and 165Hz refresh rate for smooth, responsive gaming. Features IPS panel for wide color gamut (DCI-P3 98.5%), NVIDIA G-Sync compatibility, and 1ms response time. Built with USB-C with power delivery (up to 90W), DisplayPort 1.4, and HDMI 2.0. Height, tilt, swivel, and pivot adjustable stand. Perfect for competitive gaming and professional color work.",
    features: [
      '27" QHD (2560 x 1440) Resolution',
      "165Hz Refresh Rate",
      "1ms Response Time (MPRT)",
      "NVIDIA G-Sync Compatible",
      "IPS Panel Technology",
      "USB-C with 90W Power Delivery",
      "Height Adjustable Stand",
      "Pivot & Swivel Capable",
      "VESA Mounting Compatible",
      "Audio: 2W x 2 Stereo Speakers",
    ],
    specifications: {
      Size: "27 inches",
      Resolution: "1440p (2560 x 1440)",
      "Panel Type": "IPS",
      "Refresh Rate": "165Hz",
      "Response Time": "1ms (MPRT)",
      "Color Gamut": "DCI-P3 98.5%",
      Brightness: "400 nits (typical)",
      Inputs: "USB-C (DP Alt), DisplayPort 1.4, 2x HDMI 2.0",
      Adjustments: "Height, Tilt, Swivel, Pivot",
      Power: "45W Typical",
    },
    warranty: "3 Years Premium Panel Replacement Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 5,
  },
  {
    id: "hp-pavilion-monitor",
    name: 'HP Pavilion 27" 4K Monitor',
    brand: "HP",
    category: "monitors",
    price: "125,000 KES",
    originalPrice: "145,000 KES",
    specs: '27" 4K UHD, 60Hz, IPS, HDR Support',
    rating: 4.7,
    image: "/images/products/4k-monitor.jpg",
    description:
      "Premium 4K monitor perfect for creative professionals and content creators.",
    longDescription:
      'HP Pavilion 27" 4K monitor delivers stunning visual quality with 4K UHD (3840 x 2160) resolution. Features IPS panel with 99% sRGB color accuracy, 10-bit color support, and HDR technology for enhanced contrast and realism. Includes USB-C with power delivery (65W), HDMI 2.1, and DisplayPort 1.4. Height adjustable stand with tilt, swivel, and pivot options. Ideal for photo editing, video production, and graphic design work.',
    features: [
      '27" 4K UHD (3840 x 2160) Resolution',
      "60Hz Refresh Rate",
      "IPS Panel with 99% sRGB",
      "10-bit Color Support",
      "HDR (HDR10) Technology",
      "USB-C with 65W Power Delivery",
      "Thunderbolt 3 Connectivity",
      "Height Adjustable Stand",
      "Swivel & Pivot Capable",
      "VESA Mounting",
    ],
    specifications: {
      Size: "27 inches",
      Resolution: "4K UHD (3840 x 2160)",
      "Panel Type": "IPS",
      "Refresh Rate": "60Hz",
      "Color Gamut": "99% sRGB",
      "Response Time": "5ms (GtG)",
      Brightness: "500 nits (peak)",
      Inputs: "USB-C, Thunderbolt 3, DisplayPort 1.4, HDMI 2.1",
      Adjustments: "Height, Tilt, Swivel, Pivot",
      Power: "65W Max",
    },
    warranty: "3 Years Warranty + Accidental Damage Coverage",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 4,
  },
  {
    id: "apple-studio-display",
    name: 'Apple Studio Display 27"',
    brand: "Apple",
    category: "monitors",
    price: "350,000 KES",
    originalPrice: "395,000 KES",
    specs: '27" 5K Retina, 600 nits, Nano-texture Glass',
    rating: 4.9,
    image: "/images/products/4k-monitor.jpg",
    description:
      "Professional-grade display designed for creative professionals and Apple ecosystem users.",
    longDescription:
      "Apple Studio Display features a stunning 27-inch 5K Retina display with 5120 x 2880 resolution and 600 nits brightness. Includes nano-texture glass coating to reduce glare, exceptional color accuracy (98% DCI-P3), and reference-grade HDR support. Built-in high-fidelity six-speaker system with spatial audio and three-microphone array. Includes built-in A13 Bionic chip for reference monitoring and automatic brightness adjustment. Perfect for designers, video editors, and creatives working in professional color-critical environments.",
    features: [
      '27" 5K Retina Display',
      "5120 x 2880 Resolution",
      "600 nits Brightness",
      "Nano-texture Glass Coating",
      "98% DCI-P3 Color Gamut",
      "Reference-grade HDR",
      "6-Speaker System with Spatial Audio",
      "3-Mic Array for Clear Audio",
      "A13 Bionic Chip Built-in",
      "Thunderbolt 3 Connectivity",
      "Auto Brightness Adjustment",
      "macOS & iPad Compatible",
    ],
    specifications: {
      Size: "27 inches",
      Resolution: "5K (5120 x 2880)",
      "Panel Type": "LED-backlit LCD",
      Brightness: "600 nits (typical)",
      "Color Gamut": "DCI-P3 98%",
      Contrast: "1,000,000:1 (typical)",
      Inputs: "Thunderbolt 3 (supports up to 120GB/s)",
      Audio: "6-Speaker System, 3-Mic Array",
      Power: "100W USB-C Power Delivery",
      Adjustments: "Tilt & Height Adjustable",
    },
    warranty: "1 Year Limited Warranty + AppleCare+ Available",
    availability: "In Stock (Special Order)",
    inStock: true,
    stockQuantity: 2,
  },
  {
    id: "dell-ultrawide-34",
    name: "Dell S3422DW Ultrawide Monitor",
    brand: "Dell",
    category: "monitors",
    price: "145,000 KES",
    originalPrice: "165,000 KES",
    specs: '34" Curved, 3440x1440, 100Hz, IPS',
    rating: 4.8,
    image: "/images/products/ultrawide-monitor.jpg",
    description:
      "Immersive ultrawide curved display for enhanced productivity and gaming.",
    longDescription:
      "Dell S3422DW is a 34-inch curved ultrawide monitor with 3440 x 1440 resolution, perfect for multitasking and immersive gaming. Features 100Hz refresh rate, 1ms response time, curved IPS panel for wide viewing angles, and Thunderbolt 3 with power delivery. USB-C connectivity allows single-cable connection to laptops and displays up to 90W power. Highly adjustable stand with height, tilt, swivel, and pivot options. Ideal for productivity professionals, traders, and competitive gamers.",
    features: [
      '34" Curved Ultrawide Display',
      "3440 x 1440 Resolution",
      "100Hz Refresh Rate",
      "1ms Response Time",
      "IPS Panel Technology",
      "Thunderbolt 3 with 90W Power",
      "USB-C Single Cable Connection",
      "Height Adjustable Stand",
      "Pivot, Swivel, Tilt Options",
      "Picture-by-Picture & Picture-in-Picture Modes",
    ],
    specifications: {
      Size: "34 inches",
      Resolution: "3440 x 1440 (21:9)",
      "Panel Type": "Curved IPS",
      "Refresh Rate": "100Hz",
      "Response Time": "1ms (MPRT)",
      "Color Gamut": "DCI-P3 98.5%",
      Curve: "3800R",
      Inputs: "Thunderbolt 3, DisplayPort 1.4, 2x HDMI 2.0",
      Adjustments: "Height, Tilt, Swivel, Pivot",
      Power: "90W USB-C Power Delivery",
    },
    warranty: "3 Years Premium Panel Replacement",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 3,
  },

  // PRINTERS - HP, Epson
  {
    id: "hp-envy-4520",
    name: "HP Envy 4520 Multifunction Printer",
    brand: "HP",
    category: "printers",
    price: "35,000 KES",
    originalPrice: "42,000 KES",
    specs: "Inkjet, Print/Scan/Copy/Fax, Wireless, Mobile Print",
    rating: 4.7,
    image: "/images/products/inkjet-printer.jpg",
    description:
      "Versatile all-in-one printer perfect for home and small office use.",
    longDescription:
      "HP Envy 4520 is a multifunction inkjet printer designed for families and small offices. Offers printing, scanning, copying, and faxing capabilities in one compact device. Features wireless connectivity with HP Smart app for mobile printing from smartphones and tablets. Prints up to 9.5 pages per minute in black and 7 pages in color. Auto-duplex printing for cost savings. Includes wireless connectivity, Ethernet, and USB options. High-yield ink cartridges available for economical printing.",
    features: [
      "Print, Scan, Copy, Fax Functions",
      "Wireless Connectivity",
      "Mobile Printing via HP Smart App",
      "Auto-Duplex Printing",
      "Up to 9.5 ppm (Black)",
      "Up to 7 ppm (Color)",
      "Optional High-Yield Cartridges",
      "Borderless Photo Printing",
      "USB & Ethernet Connectivity",
      "Compact Design",
    ],
    specifications: {
      Type: "Multifunction Inkjet",
      Functions: "Print, Scan, Copy, Fax",
      "Print Speed": "9.5 ppm (Black), 7 ppm (Color)",
      Resolution: "Up to 4800 x 1200 dpi",
      "Paper Capacity": "100 sheets",
      Connectivity: "Wireless 802.11b/g/n, USB, Ethernet",
      "Mobile Printing": "HP Smart App",
      Duplex: "Automatic",
      Memory: "64 MB",
      Footprint: "39 x 23 x 15 cm",
    },
    warranty: "1 Year Limited Warranty + HP Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 8,
  },
  {
    id: "epson-l3110",
    name: "Epson EcoTank L3110 All-in-One",
    brand: "Epson",
    category: "printers",
    price: "42,000 KES",
    originalPrice: "50,000 KES",
    specs: "Multifunction, Tank System, Wireless, High-Volume Printing",
    rating: 4.8,
    image: "/images/products/inkjet-printer.jpg",
    description:
      "Economical tank-based multifunction printer with extremely low cost-per-page.",
    longDescription:
      "Epson EcoTank L3110 features Epson's innovative EcoTank system with large-capacity ink tanks that print up to 4,500 pages in black and 7,500 pages in color before refill needed. Provides significantly lower cost-per-page compared to traditional cartridge systems. Functions include printing, scanning, and copying. Wireless connectivity allows printing from smartphones and computers. Perfect for high-volume printing homes and small offices. Includes sufficient ink for 2 years of printing.",
    features: [
      "EcoTank Ink System",
      "Print, Scan, Copy Functions",
      "Up to 4,500 Pages (Black) per Tank Refill",
      "Up to 7,500 Pages (Color) per Tank Refill",
      "Print Speed: 5.8 ppm (Black), 5.8 ppm (Color)",
      "Wireless Connectivity",
      "Mobile Printing Support",
      "Auto-Duplex Printing",
      "Max Resolution: 5760 x 1440 dpi",
      "Includes 2 Years Ink Supply",
    ],
    specifications: {
      Type: "Multifunction Inkjet",
      System: "EcoTank (Large-capacity tanks)",
      Functions: "Print, Scan, Copy",
      "Print Speed": "5.8 ppm (Black & Color)",
      Resolution: "Up to 5760 x 1440 dpi",
      "Tank Capacity": "Black 140ml, Color 70ml each",
      Connectivity: "USB, Wireless 802.11n",
      Duplex: "Automatic",
      "Paper Width": "A4 Maximum",
      Power: "9W (Operating), 0.8W (Standby)",
    },
    warranty: "2 Years Limited Warranty + Ink Tank Guarantee",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 6,
  },
  {
    id: "hp-laserjet-m405",
    name: "HP LaserJet Pro M405dn",
    brand: "HP",
    category: "printers",
    price: "95,000 KES",
    originalPrice: "115,000 KES",
    specs: "Laser, Monochrome, 38 ppm, Duplex, Network Print",
    rating: 4.9,
    image: "/images/products/laser-printer.jpg",
    description:
      "Professional monochrome laser printer for high-volume business printing.",
    longDescription:
      "HP LaserJet Pro M405dn is a monochrome laser printer engineered for busy offices and print-heavy environments. Delivers professional-quality output at 38 pages per minute with fast first-page-out time. Features automatic duplex printing for cost savings, secure printing capabilities, and network connectivity. 100,000-page monthly duty cycle ensures reliability for demanding workflows. Optional toner cartridges with XL capacity reduce consumable costs. Includes 512MB memory and comprehensive security features.",
    features: [
      "Monochrome Laser Printing",
      "Print Speed: 38 ppm",
      "Automatic Duplex Printing",
      "Fast First-Page-Out Time",
      "Network Printing (Ethernet)",
      "Secure Printing with PIN",
      "Optional High-Capacity Cartridges",
      "100,000 Pages/Month Duty Cycle",
      "Toner Save Mode for Economy",
      "Compact Footprint Design",
    ],
    specifications: {
      Type: "Monochrome Laser",
      "Print Speed": "38 ppm",
      "First-Page-Out": "Less than 4 seconds",
      Resolution: "600 x 600 dpi",
      "Monthly Duty Cycle": "100,000 pages",
      Memory: "512MB",
      Connectivity: "Ethernet 10/100 Base-TX, USB 2.0",
      Duplex: "Automatic",
      "Toner Yield": "Up to 10,000 pages (standard)",
      Power: "465W (Operating)",
    },
    warranty: "2 Years Onsite Hardware Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 4,
  },
  {
    id: "epson-l8180",
    name: "Epson EcoTank L8180 Color Printer",
    brand: "Epson",
    category: "printers",
    price: "65,000 KES",
    originalPrice: "78,000 KES",
    specs: "Color Inkjet, Tank System, Multifunction, Wireless",
    rating: 4.8,
    image: "/images/products/color-printer.jpg",
    description:
      "High-quality color tank printer ideal for professional color printing needs.",
    longDescription:
      "Epson EcoTank L8180 is a multifunction color printer with large ink tanks for reliable, economical color printing. Provides print, copy, and scan functionality with wireless connectivity for easy access. Tank system delivers ultra-low cost per color page while maintaining vibrant color quality. Borderless photo printing up to A4 size. Perfect for creative professionals, marketers, and businesses needing quality color output without excessive ink costs.",
    features: [
      "Color Tank-Based Printing",
      "Print, Scan, Copy Functions",
      "EcoTank System with Large-Capacity Tanks",
      "Ultra-Low Cost Per Color Page",
      "Print Speed: 10 ppm",
      "Wireless Connectivity",
      "Borderless Photo Printing",
      "Auto-Duplex Printing",
      "Max Resolution: 5760 x 1440 dpi",
      "Includes 2 Years Ink Supply",
    ],
    specifications: {
      Type: "Color Multifunction Inkjet",
      System: "EcoTank",
      Functions: "Print, Scan, Copy",
      "Print Speed": "10 ppm (Black & Color)",
      Resolution: "Up to 5760 x 1440 dpi",
      "Tank Capacity": "140ml (Black), 70ml each (CMY)",
      Connectivity: "USB, Wireless 802.11n",
      Duplex: "Automatic",
      "Paper Capacity": "Up to A4",
      "Color Gamut": "Excellent Color Accuracy",
    },
    warranty: "2 Years Limited Warranty + Ink Tank Guarantee",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 3,
  },

  // CCTV CAMERAS - HikVision, Dahua, CP Plus
  {
    id: "hikvision-ds-2cd2143g0-i",
    name: "HikVision DS-2CD2143G0-I Turret",
    brand: "HikVision",
    category: "cctv",
    price: "18,500 KES",
    originalPrice: "22,000 KES",
    specs: "4MP, Turret, Night Vision, PoE, IP67 Waterproof",
    rating: 4.8,
    image: "/images/products/4mp-camera.jpg",
    description:
      "Professional 4MP turret camera with excellent low-light performance and durability.",
    longDescription:
      "HikVision DS-2CD2143G0-I is a 4MP turret camera ideal for outdoor surveillance. Features infrared night vision with 30-meter range, IP67 weatherproof rating for all-weather operation, and PoE power for simplified installation. Dual-stream video encoding enables simultaneous HD and smooth playback. Wide dynamic range (WDR) technology handles mixed lighting conditions. Support for H.265+ video compression reduces bandwidth and storage requirements. Compatible with HikVision and third-party NVR systems.",
    features: [
      '4MP 1/3" CMOS Sensor',
      "IP67 Waterproof Rating",
      "IR Night Vision (30m range)",
      "PoE (Power over Ethernet)",
      "Turret Compact Design",
      "Wide Dynamic Range (WDR)",
      "H.265+ Video Compression",
      "Three-axis Adjustment",
      "Supports Mobile Monitoring",
      "Built-in Mic & Speaker",
    ],
    specifications: {
      Resolution: "4MP (2688 x 1520)",
      Sensor: '1/3" Progressive Scan CMOS',
      Lens: "2.8mm / 4mm / 6mm (Fixed)",
      "Night Vision": "IR LED, 30-meter range",
      WDR: "Yes (120dB)",
      "Video Compression": "H.265+, H.265, H.264+, H.264",
      "Frame Rate": "Up to 30fps",
      "IP Rating": "IP67 (Waterproof)",
      PoE: "Yes",
      "Operating Temp": "-40°C to +60°C",
    },
    warranty: "2 Years Manufacturer Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 15,
  },
  {
    id: "dahua-hac-hdw1200-s5",
    name: "Dahua HAC-HDW1200-S5 Starlight",
    brand: "Dahua Technologies",
    category: "cctv",
    price: "14,500 KES",
    originalPrice: "17,000 KES",
    specs: "2MP, Starlight Tech, Day-Night, IP67, Audio",
    rating: 4.7,
    image: "/images/products/hd-camera.jpg",
    description:
      "Budget-friendly 2MP camera with Starlight technology for excellent night vision.",
    longDescription:
      "Dahua HAC-HDW1200-S5 features Starlight technology allowing clear night vision with minimal illumination. The 2MP resolution provides good clarity for general surveillance. IP67 waterproof rating ensures reliable operation in outdoor environments. Over-coaxial (OC) technology simplifies installation by using existing coaxial cables. Built-in infrared LEDs deliver night vision up to 20 meters. Compact bullet design offers versatile mounting options. Excellent value for small-to-medium surveillance systems.",
    features: [
      '2MP 1/2.7" CMOS Sensor',
      "Starlight Ultra-Low Light Technology",
      "IR LED Night Vision (20m)",
      "IP67 Weatherproof",
      "Bullet Compact Design",
      "Over-Coaxial (OC) Technology",
      "Built-in Audio (Mic)",
      "Day-Night Auto Switch",
      "HD-CVI Video Interface",
      "Passive Infrared (PIR) Optional",
    ],
    specifications: {
      Resolution: "2MP (1920 x 1080)",
      Sensor: '1/2.7" Progressive Scan CMOS',
      Lens: "3.6mm (Fixed)",
      "Night Vision": "Starlight IR, 20-meter range",
      "Video Interface": "HD-CVI",
      "Frame Rate": "Up to 30fps",
      "IP Rating": "IP67 (Waterproof)",
      Power: "DC 12V",
      "Operating Temp": "-30°C to +60°C",
      Warranty: "2 Years",
    },
    warranty: "2 Years Manufacturer Warranty + Technical Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 20,
  },
  {
    id: "cpplus-cp-urd-1g01-p",
    name: "CP Plus CP-UVD-1G01-P Dome Camera",
    brand: "CP Plus",
    category: "cctv",
    price: "12,000 KES",
    originalPrice: "14,500 KES",
    specs: "1MP, Dome, IR Night Vision, PoE, Compact",
    rating: 4.6,
    image: "/images/products/2mp-camera.jpg",
    description:
      "Compact dome camera for indoor and outdoor surveillance at entry-level price.",
    longDescription:
      "CP Plus CP-UVD-1G01-P is an economical 1MP dome camera suitable for basic surveillance needs. Features infrared night vision with 20-meter range, IP66 weather resistance for both indoor and outdoor use. Compact dome design blends seamlessly with modern interiors while offering 360-degree monitoring. PoE-compatible for simplified installation. H.264 video compression reduces storage needs. Easy integration with existing IP-based security systems. Excellent choice for residential and small business applications.",
    features: [
      '1MP 1/4" CMOS Sensor',
      "Dome Compact Design",
      "IR LEDs (20m Night Vision)",
      "IP66 Weather Resistant",
      "PoE Compatible",
      "H.264 Video Compression",
      "360-Degree Monitoring",
      "Fisheye Correction",
      "Low Power Consumption",
      "Easy Installation",
    ],
    specifications: {
      Resolution: "1MP (1280 x 720)",
      Sensor: '1/4" Progressive CMOS',
      Lens: "3.6mm (Fixed)",
      "Night Vision": "IR LED, 20-meter range",
      "Video Standard": "MJPEG, H.264",
      "Frame Rate": "Up to 25fps",
      "IP Rating": "IP66",
      Power: "PoE (802.3af)",
      "Operating Temp": "-20°C to +50°C",
      Warranty: "1 Year",
    },
    warranty: "1 Year Manufacturer Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 25,
  },
  {
    id: "hikvision-nvr-system",
    name: "HikVision 4-Channel NVR Kit",
    brand: "HikVision",
    category: "cctv",
    price: "125,000 KES",
    originalPrice: "150,000 KES",
    specs: "4x 4MP Cameras + NVR, 2TB HDD, PoE Switch",
    rating: 4.8,
    image: "/images/products/cctv-kit.jpg",
    description:
      "Complete surveillance system with 4 cameras, recorder, and hard drive.",
    longDescription:
      "HikVision 4-Channel NVR Kit is a turnkey surveillance solution perfect for small businesses and residential properties. Includes 4x 4MP turret cameras with infrared night vision, 4-channel NVR with 2TB HDD for recording, PoE switch for simplified wiring, and installation accessories. The NVR supports remote viewing via smartphone app and web browser. Dual-stream technology ensures smooth playback while recording in high quality. Professional installation service available at additional cost.",
    features: [
      "4x 4MP IP Turret Cameras",
      "4-Channel Network Video Recorder",
      "2TB Hard Disk Drive",
      "PoE Switch Included",
      "All Installation Cables & Accessories",
      "Mobile Remote Viewing",
      "Motion Detection & Alerts",
      "Dual-Stream Video Technology",
      "Plug & Play Setup",
      "Professional Warranty & Support",
    ],
    specifications: {
      Cameras: "4x DS-2CD2143G0-I",
      NVR: "4-Channel, 2TB HDD",
      Resolution: "4MP (2688 x 1520)",
      "Recording Modes": "Continuous, Motion Detection, Scheduled",
      Connectivity: "Ethernet, PoE",
      Storage: "2TB (Expandable)",
      "Mobile Access": "Hik-Connect App",
      Playback: "Simultaneous Recording & Playback",
      Warranty: "2 Years Hardware + 1 Year Support",
      Installation: "DIY or Professional Service Available",
    },
    warranty: "2 Years Hardware Warranty + 1 Year Free Technical Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 3,
  },
  {
    id: "dahua-cctv-kit-5mp",
    name: "Dahua 8-Channel 5MP CCTV System",
    brand: "Dahua Technologies",
    category: "cctv",
    price: "185,000 KES",
    originalPrice: "215,000 KES",
    specs: "8x 5MP Cameras, 8-Channel DVR, 4TB HDD, Cables",
    rating: 4.8,
    image: "/images/products/cctv-kit.jpg",
    description:
      "High-resolution 8-camera CCTV system for comprehensive property surveillance.",
    longDescription:
      "Dahua 8-Channel 5MP CCTV System provides comprehensive coverage for large properties, businesses, and compounds. Includes 8x 5MP bullet cameras with advanced night vision, 8-channel DVR with 4TB HDD, surge protection, and all necessary cables. The system uses HD-CVI technology for compatibility and simplified installation. Motion detection, remote playback, and mobile app support included. Professionally recommended for farms, warehouses, manufacturing facilities, and large residential properties.",
    features: [
      "8x 5MP Bullet Cameras",
      "8-Channel Digital Video Recorder",
      "4TB Hard Disk Drive",
      "HD-CVI Technology",
      "All Installation Cables Included",
      "Surge Protection Unit",
      "Remote Mobile Viewing",
      "Motion Detection Alerts",
      "Night Vision (40m IR)",
      "Weatherproof Design",
    ],
    specifications: {
      Cameras: "8x 5MP Dahua Bullet Cameras",
      Resolution: "5MP (2560 x 1920)",
      DVR: "8-Channel HD-CVI",
      Storage: "4TB Hard Drive",
      "Night Vision": "IR LEDs, 40-meter range",
      "Frame Rate": "Up to 30fps",
      "Video Compression": "H.264, H.265",
      Connectivity: "Coaxial & Ethernet",
      Power: "DC 12V Power Supply",
      "Operating Temp": "-20°C to +60°C",
    },
    warranty: "2 Years Manufacturer Warranty + Installation Support",
    availability: "In Stock (Made to Order)",
    inStock: true,
    stockQuantity: 2,
  },

  // ACCESSORIES - Generic Popular Brands
  {
    id: "logitech-mk540",
    name: "Logitech MK540 Wireless Keyboard & Mouse",
    brand: "Logitech",
    category: "accessories",
    price: "8,500 KES",
    originalPrice: "10,000 KES",
    specs: "Wireless 2.4GHz, Long Battery, Quiet Keys",
    rating: 4.7,
    image: "/images/products/keyboard.jpg",
    description:
      "Reliable wireless keyboard and mouse combo for everyday computing.",
    longDescription:
      "Logitech MK540 is a dependable wireless combo keyboard and mouse set. Features 2.4GHz wireless connectivity with strong, reliable signal, quiet key switches for noiseless typing, and responsive mouse tracking. Long battery life (up to 3 years for keyboard, 18 months for mouse) reduces replacements. Compact design fits well in tight spaces. USB nano-receiver eliminates cable clutter. Compatible with Windows and Mac computers.",
    features: [
      "Wireless 2.4GHz Connection",
      "Quiet Key Switches",
      "Responsive Optical Mouse",
      "Long Battery Life",
      "Compact Design",
      "USB Nano-Receiver",
      "Windows & Mac Compatible",
      "Durable ABS Plastic Build",
      "Standard Layout Keys",
      "Plug-and-Play Setup",
    ],
    specifications: {
      Connection: "Wireless 2.4GHz",
      "Keyboard Battery": "2x AAA Batteries (up to 3 years)",
      "Mouse Battery": "1x AA Battery (up to 18 months)",
      "Mouse Resolution": "1000 DPI",
      "Operating Range": "Up to 10 meters",
      Compatibility: "Windows, macOS, Linux",
      "Keyboard Keys": "105 Keys (QWERTY)",
      "Receiver Type": "USB Nano",
      Weight: "Keyboard 750g, Mouse 110g",
      Warranty: "2 Years",
    },
    warranty: "2 Years Manufacturer Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 18,
  },
  {
    id: "corsair-k65-rgb",
    name: "Corsair K65 RGB Mechanical Keyboard",
    brand: "Corsair",
    category: "accessories",
    price: "22,500 KES",
    originalPrice: "27,000 KES",
    specs: "Mechanical, RGB Backlighting, Cherry MX Switches, USB",
    rating: 4.8,
    image: "/images/products/keyboard.jpg",
    description:
      "Premium gaming keyboard with mechanical switches and customizable RGB lighting.",
    longDescription:
      "Corsair K65 RGB is a high-quality gaming keyboard featuring cherry MX mechanical switches for superior tactile feedback and durability. Full RGB backlighting with millions of color options customizable via iCUE software. Compact 60% layout reduces desk space while maintaining full functionality. Aluminum frame construction ensures durability. Fast actuation and low profile keys for competitive gaming. USB wired connection provides stable communication without latency.",
    features: [
      "Cherry MX Mechanical Switches",
      "Full RGB Backlighting",
      "iCUE Software Control",
      "Aluminum Frame Construction",
      "Compact 60% Layout",
      "100% NKRO (N-Key Rollover)",
      "USB Wired Connection",
      "Quick Release USB Cable",
      "Programmable Keys",
      "Gaming Profile Support",
    ],
    specifications: {
      "Switch Type": "Cherry MX (Red/Blue/Brown Options)",
      Layout: "60% Compact",
      Backlighting: "Per-Key RGB",
      Connection: "USB Wired",
      "Cable Length": "1.8m Braided Cable",
      Material: "Aluminum Frame, ABS Keycaps",
      "Key Lifespan": "50 Million Keystrokes",
      "Polling Rate": "8000Hz",
      Weight: "680g",
      Compatibility: "Windows, macOS",
    },
    warranty: "5 Years Hardware Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 6,
  },
  {
    id: "razer-deathadder-v3",
    name: "Razer DeathAdder V3 Gaming Mouse",
    brand: "Razer",
    category: "accessories",
    price: "18,500 KES",
    originalPrice: "22,000 KES",
    specs: "30000 DPI, Wireless, Focus Pro 30K Sensor, Lightweight",
    rating: 4.8,
    image: "/images/products/gaming-mouse.jpg",
    description:
      "Professional-grade gaming mouse with ultra-high precision and fast wireless connection.",
    longDescription:
      "Razer DeathAdder V3 features Razer Focus Pro 30K sensor for pixel-perfect precision up to 30,000 DPI. Fast 2.4GHz wireless connection with 65-hour battery life. Lightweight ergonomic design reduces hand fatigue during long gaming sessions. 8 programmable buttons customizable via Razer Synapse software. Advanced grip texture prevents hand slipping. Winner of multiple gaming hardware awards.",
    features: [
      "Razer Focus Pro 30K Sensor",
      "Up to 30,000 DPI Precision",
      "2.4GHz Wireless Connection",
      "65-Hour Battery Life",
      "Lightweight Ergonomic Design",
      "8 Programmable Buttons",
      "Razer Synapse Software",
      "Advanced Grip Texture",
      "Optical Switches (faster clicks)",
      "Award-Winning Design",
    ],
    specifications: {
      Sensor: "Razer Focus Pro 30K",
      "DPI Range": "100 - 30,000 DPI",
      Connection: "2.4GHz Wireless",
      "Polling Rate": "8000Hz (Wireless)",
      "Battery Life": "65 Hours",
      "Charging Time": "2 Hours",
      Buttons: "8 Programmable",
      Grip: "Rubberized Side Grips",
      Weight: "63g",
      Color: "Black",
    },
    warranty: "2 Years Warranty + Razer Support",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 8,
  },
  {
    id: "belkin-usb-c-hub",
    name: "Belkin 7-in-1 USB-C Hub",
    brand: "Belkin",
    category: "accessories",
    price: "12,500 KES",
    originalPrice: "15,000 KES",
    specs: "USB-C, 7 Ports, 4K HDMI, 100W Power Delivery",
    rating: 4.7,
    image: "/images/products/usb-hub.jpg",
    description:
      "Versatile USB-C hub expanding connectivity for modern laptops.",
    longDescription:
      "Belkin 7-in-1 USB-C hub provides comprehensive connectivity expansion for USB-C enabled laptops and devices. Includes 4K HDMI output, 3x USB-A 3.1 ports, SD/microSD card readers, and 100W USB-C power delivery. Aluminum construction provides durability while remaining compact. Supports simultaneous charging and data transfer. Compatible with MacBooks, Dell, HP, Lenovo, and other USB-C devices.",
    features: [
      "7 Ports in 1 Compact Hub",
      "4K HDMI Video Output",
      "3x USB-A 3.1 Ports",
      "SD/microSD Card Reader",
      "100W USB-C Power Delivery",
      "Aluminum Construction",
      "Hot-Swap Compatible",
      "Plug-and-Play Setup",
      "Braided USB-C Cable",
      "Multi-Device Support",
    ],
    specifications: {
      Ports: "1x USB-C (Input), 3x USB-A 3.1, 1x HDMI, 1x SD, 1x microSD",
      HDMI: "4K @ 60Hz",
      "USB Power Delivery": "100W",
      "Data Transfer": "USB 3.1 5Gbps",
      "Card Readers": "SD/microSD UHS-II",
      Material: "Aluminum",
      "Cable Length": "0.3m Braided",
      Compatibility: "USB-C Devices (MacBook, iPad Pro, etc)",
      Color: "Space Gray/Silver",
      Warranty: "2 Years",
    },
    warranty: "2 Years Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 12,
  },
  {
    id: "coolermaster-laptop-pad",
    name: 'Cooler Master 17" Laptop Cooling Pad',
    brand: "Cooler Master",
    category: "accessories",
    price: "6,500 KES",
    originalPrice: "8,000 KES",
    specs: "Dual Fans, USB Powered, Adjustable Stand",
    rating: 4.6,
    image: "/images/products/cooling-pad.jpg",
    description:
      "Effective cooling solution for laptops during gaming and heavy workloads.",
    longDescription:
      'Cooler Master 17" laptop cooling pad features dual 12cm fans that reduce laptop temperature by up to 10 degrees. USB powered with quiet operation (21dB). Aluminum mesh surface with 4 height adjustment levels for ergonomic comfort. Supports laptops up to 17 inches. Compact design fits under laptops without taking excessive desk space. Essential for gaming notebooks and preventing thermal throttling.',
    features: [
      "Dual 12cm Cooling Fans",
      "USB Powered (No AC adapter needed)",
      "Aluminum Mesh Surface",
      "4-Level Height Adjustment",
      'Supports Up to 17" Laptops',
      "Quiet Operation (21dB)",
      "Compact Footprint",
      "Non-slip Rubber Base",
      "Improves Laptop Performance",
      "Extended USB Cable (1.5m)",
    ],
    specifications: {
      Size: "395 x 295 x 25-60mm",
      Fans: "2x 12cm",
      "Air Flow": "2.5 CFM per Fan",
      "Noise Level": "Below 21dB",
      Power: "USB 5V (Single USB port)",
      Material: "Aluminum Mesh",
      "Height Adjustment": "4 Levels",
      Compatibility: 'Laptops up to 17"',
      "Cable Length": "1.5m USB Cable",
      Weight: "680g",
    },
    warranty: "2 Years Warranty",
    availability: "In Stock",
    inStock: true,
    stockQuantity: 14,
  },
];

export function getProductById(id: string): Product | undefined {
  return productsData.find((product) => product.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return productsData.filter((product) => product.category === category);
}

export function getProductsByBrand(brand: string): Product[] {
  return productsData.filter((product) => product.brand === brand);
}
